name:                resheet
version:             0.1.0.0
github:              "talanis85/resheet"
license:             BSD3
author:              "Philip Kranz"
maintainer:          "Philip Kranz <pk@pmlk.net>"
copyright:           "2019 Philip Kranz"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
synopsis:            Generate musical lead sheets from a simple plain text format
category:            Music

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/talanis85/resheet#readme>

default-extensions:
  - OverloadedStrings

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  exposed-modules:
    - Data.Resheet
    - Data.Resheet.Parser
  dependencies:
    - containers
    - haScales
    - mtl
    - parsec
    - text

executables:
  resheet:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - resheet
    - text

tests:
  resheet-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - resheet
